### ISSUE TITLE
tutorial for building  / running examples

### ISSUE THREAD

**Issue by haochenuw** [lca1/lattigo#5]
can we have such tutorials for first time go users?

**Comment by Pro7ech** [comment]
There is no special requirement to build/run go code.  Open the console, cd / to the folder containing the file of the example you want to run and enter :

go run <nameofexamplefile>.go 

in the console

**Comment by haochenuw** [comment]
$ go run examples_bfv.go
bash: go: command not found

**Comment by Pro7ech** [comment]
Well, obviously you need to install Go : https://golang.org/dl/

**Comment by ChristianMct** [comment]
Hey Hao and thanks for your interest. [https://gobyexample.com/](gobyexample.com) is also a good introduction to the Go language.
